server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/stefany9229/confifuracionesParcial1Backend.git'
          default-label: main
          force-pull: true